In [2]:
import torch
import torch.nn as nn

In [3]:
# 输入的特征向量的维度是6
# 有两层MLP 第一层的输出维度是4
# 第二层的输出维度是2
# 最终的输出维度是1
class MyMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(6,4)
        self.activationFunction = nn.ReLU()
        self.linear2 = nn.Linear(4,2)
        self.linear3 = nn.Linear(2,1)
        self.activation2 = nn.Softmax()
    def forward(self,x):
        y = self.linear1(x) #1 * 4
        y = self.activationFunction(y)
        y = self.linear2(y)
        y = self.activationFunction(y)
        y = self.linear3(y)
        return y


In [4]:
x = torch.randn(1,6) #生成一个模拟的输入 pytorch tensor
model = MyMLP()      #初始化模型，创建了一个实例
y = model(x)         # 输入到输出
print(y.shape,y)

torch.Size([1, 1]) tensor([[0.2972]], grad_fn=<AddmmBackward0>)


In [8]:
class MyMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(6,4),
            nn.ReLU(),
            nn.Linear(4,2),
            nn.ReLU(),
            nn.Linear(2,1),
        )
    def forward(self,x):
        y = self.mlp(x)
        return y

In [13]:
x = torch.randn(1,6) #生成一个模拟的输入 pytorch tensor
model = MyMLP()      #初始化模型，创建了一个实例
y = model(x)         # 输入到输出
print(y.shape,y)

torch.Size([1, 1]) tensor([[0.3172]], grad_fn=<AddmmBackward0>)


In [10]:
x = torch.randn(10,3,3,3)

In [11]:
torch.cat() #进行拼接
torch.transpose()#指明哪两个维度需要exchange调换
x.contiguous() #连续化  改变了多维数组在内存中的存储顺序，以便配合view方法使用
x.view() #view()之后的张量与原张量共享内存，并且是连续的,重新定义了访问张量的规则，使得取出的张量按照我们希望的形状展现，没改变形状
x.reshape() #与原数据量相同，不改变原tensor
tensor.to(dtype=, device=)  #points_cpu = points_gpu.to(device='cpu') 数据tensor拷贝到device GPU上

SyntaxError: invalid syntax (1028874312.py, line 6)

In [ ]:
torch.randn(8, 3, 244, 244)
#[batch, channel, height, width]，表示batch_size=8， 3通道（灰度图像为1），图片尺寸：224x224  

In [14]:
a = torch.randn(4,3,2)
b=torch.cat((x,x),0) 
c=torch.cat((x,x),1)
print(a,b,c)
#dim=0,按行拼接
#dim=1,按列拼接
#dim=2,按第三维度深度进行拼接

tensor([[[-1.4513,  0.8483],
         [ 0.1963, -0.4604],
         [ 0.0674,  0.9368]],

        [[-0.8874,  2.5921],
         [ 1.1785, -1.1816],
         [ 0.1961,  1.5274]],

        [[-0.6934, -1.4621],
         [ 0.3626,  0.0578],
         [-1.2352, -0.0527]],

        [[ 0.7771, -0.2380],
         [-0.6919, -0.7696],
         [ 0.3134, -1.2343]]]) tensor([[-0.4497, -0.5642,  0.3265, -0.1272,  0.6068,  0.2357],
        [-0.4497, -0.5642,  0.3265, -0.1272,  0.6068,  0.2357]]) tensor([[-0.4497, -0.5642,  0.3265, -0.1272,  0.6068,  0.2357, -0.4497, -0.5642,
          0.3265, -0.1272,  0.6068,  0.2357]])


In [15]:
t = torch.tensor([[2, 1, 3], [4, 5, 9]])
print(t)
print(t.view(-1))

tensor([[2, 1, 3],
        [4, 5, 9]])
tensor([2, 1, 3, 4, 5, 9])
